using Xunit;
using Conway.File;
using Conway.Matrix;

namespace Conway.Test {
    public class Test{
                    string glider=@"........................X...........
......................X.X...........
............XX......XX............XX
...........X...X....XX............XX
XX........X.....X...XX..............
XX........X...X.XX....X.X...........
..........X.....X.......X...........
...........X...X....................
............XX......................
";
        [Fact]
        public void ReadHeader()
        {
            var rle = new Rle();
            rle.Load(@"Patterns/glider.rle");
        }

        [Fact]
        public void GliderVaca()
        {
            var vaca = new Vaca("Patterns/Glider.vaca");
            Assert.Equal(glider,vaca.ConwayMatrix.ToString());
        }

        [Fact]
        public void GliderMatrix()
        {
            var rle = new Rle();
            rle.Load(@"Patterns/glider.rle");
            Assert.Equal(glider,rle.ConwayMatrix.ToString());
        }

        [Fact]
        public void SixBitsMatrix()
        {
            string sixbits=@".....................X..................
.....................X..................
....................X.X.................
.....................X..................
.....................X..................
.....................X..................
.....................X..................
....................X.X.................
.....................X..................
.....................X..................
..X..X....X..X..........................
XXX..XXXXXX..XXX........................
..X..X....X..X..........................
......................XX................
.....................XX.................
.......................X................
................................X....X..
..............................XX.XXXX.XX
................................X....X..
........................................
........................................
........................................
........................................
";
            var rle = new Rle();
            rle.Load("Patterns/6bits.rle");
            Assert.Equal(sixbits,rle.ConwayMatrix.ToString());
        }

        [Fact]
        public void TestMatrix()
        {
            string test1 = @"....
....
....
....
";
            string test2 = @".....
.....
.....
.....
....X
";
            string test3 = @"X.....
......
......
......
......
.....X
";
            string test4 = @"X......
.......
.......
.......
......X
.....X.
";
            string test5 = @"X......
.......
.......
.......
......X
.....X.
....X..
";
            var matrix = new ConwayMatrix();
            matrix.SetSize(4,4);
            Assert.Equal(test1,matrix.ToString());
            matrix[4,4] = true;
            Assert.Equal(test2,matrix.ToString());
            matrix[-1,-1] = true;
            Assert.Equal(test3,matrix.ToString());
            matrix[4,6] = true;
            Assert.Equal(test4,matrix.ToString());
            matrix[6,4] = true;
            Assert.Equal(test5,matrix.ToString());
        }
    }
}