using Xunit;
using Conway.File;
using Conway.Matrix;

namespace Conway.Test {
    public class TestRle{
        [Fact]
        public void ReadHeader()
        {
            var rle = new Rle();
            rle.Load(@"Patterns/glider.rle");
        }

        [Fact]
        public void TestMatrix()
        {
            string test1 = @"....
....
....
....
";
            string test2 = @".....
.....
.....
.....
....X
";
            string test3 = @"X.....
......
......
......
......
.....X
";
            string test4 = @"X......
.......
.......
.......
......X
.....X.
";
            string test5 = @"X......
.......
.......
.......
......X
.....X.
....X..
";
            var matrix = new ConwayMatrix();
            matrix.SetSize(4,4);
            Assert.Equal(test1,matrix.ToString());
            matrix[4,4] = true;
            Assert.Equal(test2,matrix.ToString());
            matrix[-1,-1] = true;
            Assert.Equal(test3,matrix.ToString());
            matrix[4,6] = true;
            Assert.Equal(test4,matrix.ToString());
            matrix[6,4] = true;
            Assert.Equal(test5,matrix.ToString());
        }
    }
}