version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - ps: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - ps: dotnet --version
  # Display minimal restore text
  - ps: dotnet restore ./Conway.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - ps: dotnet publish ./Conway.csproj
after_build:
  # For once the build has completed
  - ps: 7z a Conway.zip %APPVEYOR_BUILD_FOLDER%\Conway\bin\Debug\netcoreapp2.1\publish\*
artifacts:
 - path: Conway.zip
   name: Conway 
   type: Zip
clone_depth: 1
test_script:
  - ps: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off
